[build]
  command = "npm run build"
  publish = "dist"

# Configuración para desarrollo local
[dev]
  command = "npm run dev"
  publish = "dist"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

